### ISSUE TITLE
Double encoding of @

### ISSUE THREAD

**Issue by wexi79** [sys4/automx#12]
I set up automx but it failed to provide settings for Thunderbird 31, however automx-test passed OK. I looked at the debugging output and noticed that the email address provided by Thunderbird had for some reason been double encoded to "something%2540example.com" and was still encoded as "something%40example.com" when passed to config.py with data.configure(emailaddress, cn, password) in automx_wsgi.py on line 211 (version 0.10.2). I did a crude fix by just doing a replace for "%40" with "@" as I was in a hurry but you probably can fix this issue where the double encoding originally takes place.

**Comment by bwurst** [comment]
I encountered this issue as well. Exactly the same behaviour here, with Thunderbird 31.

Seems like a bug in Thunderbird but I think it should be worked around in automx.
