### ISSUE TITLE
Autodiscover does not work

### ISSUE THREAD

**Issue by chicobico** [sys4/automx#17]
Autodiscover does not work on a Windows 8 Machine.
Any Idea?
The Log is clean without any error.
When i call https://autodiscover.automx.org/autodiscover/autodiscover.xml i only get a blank site.

**Comment by croessner** [comment]
I will check this. Maybe something is broken with our test site

**Comment by muelli** [comment]
`Host autodiscover.automx.org not found: 3(NXDOMAIN)`

**Comment by muelli** [comment]
so.. no test site any more?

**Comment by patrickbenkoetter** [comment]
> so.. no test site any more?

There will be one soon again and a few other nice enhancements. ;-)
