### ISSUE TITLE
Self containing install

### ISSUE THREAD

**Issue by kevinvalk** [sys4/automx#21]
I do not know enough of the Python standards and best practices to know if what I did is blasphemy, but here it goes.

I wanted to have a self containing installation of automx, so without copying files throughout the system. To achieve this, I just added two lines to automx_wsgi.py. This will add the current directory to the search path for libraries so we do not have to copy the automx libraries to the system wide install (or virtualenv). 
```
import sys,os
sys.path.append(os.path.dirname(os.path.realpath(__file__)))
```
Now I can just make a script alias to ```automx/src/automx_wsgi.py``` directly. The only thing I have to copy is the automx.conf.

Anyways, adding these two lines does not break any existing installation and does help new installations. But once again, I know nothing of standards for Python.

Good stuff!

**Comment by croessner** [comment]
Good idea :-) I just added it. Thanks
