### ISSUE TITLE
centos6 not working

### ISSUE THREAD

**Issue by extremeshok** [sys4/automx#23]
Syntax errors with the latest git on centos 6

Any help / ideas would be appreciated.

Thanks

/var/log/uwsgi/uwsgi.log

```
*** Operational MODE: single process ***
added /usr/lib/automx/src/ to pythonpath.
  File "/usr/lib/automx/src/automx_wsgi.py", line 68
    print(e, file=environ["wsgi.errors"])
                 ^
SyntaxError: invalid syntax
unable to load app 0 (mountpoint='') (callable not found or import error)
```

python -V

```
Python 2.6.6
```

/etc/uwsgi.d/automx.ini

```
[uwsgi]
plugins = python
vhost = true

socket = 127.0.0.1:7000
pidfile = /var/run/uwsgi.automx.pid
chown-socket = nginx:nginx
chmod-socket = 660
uid = automx
gid = automx
enable-threads = true

module = automx_wsgi

python-path = /usr/lib64/python2.6
file = /usr/local/lib/automx/automx_wsgi.py
```

**Comment by extremeshok** [comment]
Is python 2.6.6 no longer supported ? ie. no longer compatible with a vanilla centos 6

**Comment by croessner** [comment]
The master branch currently requires Python 3. But the stable releases should all work with Python 2.6+

**Comment by extremeshok** [comment]
You pretty much that exclude Centos 6/7 , Debian 6/7/8 and default releases of ubuntu.

Why not mention this in your docs ?

Your stable releases are 18months old and you did not fork the last compatible commit of 2.6.

**Comment by croessner** [comment]
The master branch is a work in progress. The "old" stable releases still meet current state. So this branch is a beginning towards Python 3, next step is to make it compatible to Python 2.7. But I had to port it first to find out where the differences are in 2.7 and 3.

Ubuntu and Debian by the way are compatible with the master branch as they contain Python 3
