### ISSUE TITLE
Mismatch: Latest official version

### ISSUE THREAD

**Issue by b-pfl** [sys4/automx#25]
The Changelog of the master branch (https://github.com/sys4/automx/blob/master/CHANGES) states that the latest version is 0.10.3. However, the latest official version provided at https://github.com/sys4/automx/releases/latest is still 0.10.2.

**Comment by croessner** [comment]
You are right. The current master branch is a work in progress. I ported it to Python 3 and have tested it for a while now. Not all functionality is working in Py3. As I have done several other projects now, I "learned" on how to optimize code that it works from Py3.7 up to Py3. So I will try to make the code work with older Python. After that I will release a new version and that will not be 0.10.3. I promise that the 0.10.2 and the current branch do not differ in functionality. Please be patient.

**Comment by croessner** [comment]
I tryed to make the code Py2.7 and Py3.x compatible. I finished my work and I will test it tomorrow. If it works for me, I will commit the changes and ask to give this stage a test.
