### ISSUE TITLE
Autodetect MX with Fallback automx_script

### ISSUE THREAD

**Issue by chicobico** [sys4/automx#26]
Thank you for your nice tool.
On our mailserver it´s necessary that automx dynamically detects the MX-Record from the requested domain to return the perfect configuration.
I´ve build a small automx-script for this problem.

Maybe it´s interesting for the automx repository as example script!?

The script takes the first argument and detects the primary MX-Record.
The second argument is used as fallback if the MX detection gets an timeout or other exception.

```
#!/usr/bin/python

import dns.resolver
import re
import sys

domain = str(sys.argv[1])

try:
    mx_objects = dns.resolver.query(domain,'MX')
except:
    print str(sys.argv[2])
    sys.exit(0)

mx_server = {}

for server in mx_objects:
    mx_server[server.preference] = server.exchange

primary_mx_server = re.sub('\.$', '', mx_server[sorted(mx_server)[0]].to_text())

print primary_mx_server
```

**Comment by croessner** [comment]
Sorry for the late response. I will include this script as "contrib". Can you please tell me, which package contains dns.resolver? So I can write a little README. Also if you want your name as author be included, please drop me a note. Thank you very much for your message and your code example :-)

**Comment by chicobico** [comment]
The package is [https://github.com/rthalley/dnspython](dnspython). You can add my company as author ".webflow GmbH"
