### ISSUE TITLE
[Mobileconfig] openssl: unable to write 'random state'

### ISSUE THREAD

**Issue by HansVanEijsden** [sys4/automx#27]
First of all, thanks for automx!

Everything works, except the signing of the profiles generated by mobileconfig.
It doesn't include the certificate path, only the leaf cert, because of an error: "openssl: unable to write 'random state'".
I use this (up to date) Github source, and OpenSSL 1.0.2g.

I also tried to run automx as root for one minute, but then the same error (so it's not a permissions issue I think). I already removed all the .rnd files on the system to be sure.. still that error.

See the attached (anonymized to example.com) log file. I hope you can point me in the right direction. 😃 Thnx!
[automxlog.txt](https://github.com/sys4/automx/files/193834/automxlog.txt)

**Comment by croessner** [comment]
The random seed error is not the reason :-) For this, you need to define the variable "homedir" in your automx.conf file, which should point to a directory, where the automx user has write permissions to.

**Comment by croessner** [comment]
Concerning the signing problem I guess that you have an error in automx.conf, too:

Mine looks like this:

sign_mobileconfig = yes
sign_cert = /etc/ssl/certs/www.roessner-net.de.crt
sign_key = /etc/ssl/private/www.roessner-net.de.key
sign_more_certs = /etc/ssl/certs/www.roessner-net.de.crt

Th2 sign_more_certs option is like a ca file, but it carries all certificates. Unfortunatelly, I can not make this easier.

It has the following structure at my setup:

-----BEGIN CERTIFICATE-----
Your certificate
-----END CERTIFICATE-----
-----BEGIN DH PARAMETERS-----
A 2048 bit DH params file
-----END DH PARAMETERS-----
-----BEGIN CERTIFICATE-----
Intermediate CA
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
CA
-----END CERTIFICATE-----

If you get a signing error, I think that there are missing intermediate certs.

**Comment by croessner** [comment]
The code is frozen. Documentation needs updates before next beta :-)

**Comment by HansVanEijsden** [comment]
@croessner wow, great quick replies, thanks!
Your first suggestion about homedir didn't solve the random state "issue", but it doesn't seem to be an issue indeed.

sign_more_certs did the trick! Perfect! I included the intermediate chain in sign_cert but that didn't work, but in sign_more_certs it works perfect. Green! 👍

**Comment by croessner** [comment]
:-)

**Comment by GoodbyeWorld** [comment]
Both a writeable `homedir = /var/www/site` and `sign_more_certs = /some/chain.pem` pointing to a file with the cert + full chain fixed my issue.
