### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by jpaechnatz** [sys4/automx#29]
I'm using a Centos 7 Host. I followed your INSTALL doc.
The following python packages are installed but it still complains about missing modules:

python-2.7.5-34.el7.x86_64
python2-boto-2.39.0-1.el7.noarch
python2-crypto-2.6.1-9.el7.x86_64
python2-ecdsa-0.13-4.el7.noarch
python2-paramiko-1.16.1-1.el7.noarch
python2-rsa-3.4.1-1.el7.noarch
python-backports-1.0-8.el7.x86_64
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-chardet-2.2.1-1.el7_1.noarch
python-configobj-4.7.2-7.el7.noarch
python-dateutil-1.5-7.el7.noarch
python-decorator-3.4.0-3.el7.noarch
python-GnuPGInterface-0.3.2-11.el7.noarch
python-iniparse-0.4-9.el7.noarch
python-ipaddr-2.1.9-5.el7.noarch
python-IPy-0.75-6.el7.noarch
python-javapackages-3.4.1-11.el7.noarch
python-kitchen-1.1.1-5.el7.noarch
python-libs-2.7.5-34.el7.x86_64
python-lockfile-0.9.1-4.el7.centos.noarch
python-lxml-3.2.1-4.el7.x86_64
python-memcached-1.48-4.el7.noarch
python-perf-3.10.0-327.18.2.el7.x86_64
python-pyasn1-0.1.6-2.el7.noarch
python-pycurl-7.19.0-17.el7.x86_64
python-pyudev-0.15-7.el7_2.1.noarch
python-requests-2.6.0-1.el7_1.noarch
python-setuptools-0.9.8-4.el7.noarch
python-six-1.9.0-2.el7.noarch
python-slip-0.4.0-2.el7.noarch
python-slip-dbus-0.4.0-2.el7.noarch
python-urlgrabber-3.10-7.el7.noarch
python-urllib3-1.10.2-2.el7_1.noarch

Error in httpd/apache log:
[Mon Jun 06 11:45:09.807617 2016] [:error] [pid 15232] [client 78.46.79.43:38182] mod_wsgi (pid=15232): Target WSGI script '/usr/lib/automx/automx_wsgi.py' cannot be loaded as Python module.
[Mon Jun 06 11:45:09.807642 2016] [:error] [pid 15232] [client 78.46.79.43:38182] mod_wsgi (pid=15232): Exception occurred processing WSGI script '/usr/lib/automx/automx_wsgi.py'.
[Mon Jun 06 11:45:09.807655 2016] [:error] [pid 15232] [client 78.46.79.43:38182] Traceback (most recent call last):
[Mon Jun 06 11:45:09.807666 2016] [:error] [pid 15232] [client 78.46.79.43:38182]   File "/usr/lib/automx/automx_wsgi.py", line 29, in <module>
[Mon Jun 06 11:45:09.807749 2016] [:error] [pid 15232] [client 78.46.79.43:38182]     from html import escape
[Mon Jun 06 11:45:09.807763 2016] [:error] [pid 15232] [client 78.46.79.43:38182] ImportError: No module named html

sys.path
python
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import sys
> > > sys.path
> > > ['', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']
> > > import html
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named html
> > > import escape
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named escape

What I am missing?

**Comment by croessner** [comment]
If you installed from the master branch, you installed a first beta, which is okay so far. This release needs updated documentation. To solve your problem, you probably need to install the python "future" package. I am not sure, if it is part of CentOS, but at least you could install it with

pip install future

...ok, just checked Centos. The package is named python-futures.noarch. Üöease try it and report back

**Comment by jpaechnatz** [comment]
installed. still same error.
[Mon Jun 06 14:04:59.084257 2016] [:error] [pid 25125] [client 62.206.86.158:55686] mod_wsgi (pid=25125): Target WSGI script '/usr/lib/automx/automx_wsgi.py' cannot be loaded as Python module.
[Mon Jun 06 14:04:59.084276 2016] [:error] [pid 25125] [client 62.206.86.158:55686] mod_wsgi (pid=25125): Exception occurred processing WSGI script '/usr/lib/automx/automx_wsgi.py'.
[Mon Jun 06 14:04:59.084289 2016] [:error] [pid 25125] [client 62.206.86.158:55686] Traceback (most recent call last):
[Mon Jun 06 14:04:59.084301 2016] [:error] [pid 25125] [client 62.206.86.158:55686]   File "/usr/lib/automx/automx_wsgi.py", line 29, in <module>
[Mon Jun 06 14:04:59.084367 2016] [:error] [pid 25125] [client 62.206.86.158:55686]     from html import escape
[Mon Jun 06 14:04:59.084380 2016] [:error] [pid 25125] [client 62.206.86.158:55686] ImportError: No module named html

**Comment by jpaechnatz** [comment]
Any news?

**Comment by croessner** [comment]
I tried to reproduce this.


rns root@sogo ~ # python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from html import escape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named html
>>> import future
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named future
>>>
rns root@sogo ~ # yum search future
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.hosteurope.de
 * epel: ftp.uni-stuttgart.de
 * extras: ftp.hosteurope.de
 * updates: ftp.hosteurope.de
============================================================================= N/S matched: future =============================================================================
python-futures.noarch : Backport of the concurrent.futures package from Python 3.2
python2-future.noarch : Easy, clean, reliable Python 2/3 compatibility
rubygem-vcr.noarch : Record test suite HTTP interactions and replay during future test runs

  only-Übereinstimmungen in Name und Zusammenfassung, «Alles suchen» für vollständige Suche.
rns root@sogo ~ # yum -y install python2-future.noarch
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.hosteurope.de
 * epel: ftp.uni-stuttgart.de
 * extras: ftp.hosteurope.de
 * updates: ftp.hosteurope.de
Abhängigkeiten werden aufgelöst
--> Transaktionsprüfung wird ausgeführt
---> Paket python2-future.noarch 0:0.15.2-7.el7 markiert, um installiert zu werden
--> Abhängigkeitsauflösung beendet

Abhängigkeiten aufgelöst

===============================================================================================================================================================================
 Package                                        Arch                                   Version                                      Paketquelle                          Größe
===============================================================================================================================================================================
Installieren:
 python2-future                                 noarch                                 0.15.2-7.el7                                 epel                                 797 k

Transaktionsübersicht
===============================================================================================================================================================================
Installieren  1 Paket

Gesamte Downloadgröße: 797 k
Installationsgröße: 3.6 M
Downloading packages:
python2-future-0.15.2-7.el7.noarch.rpm                                                                                                                  | 797 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installieren     : python2-future-0.15.2-7.el7.noarch                                                                                                                    1/1
  Überprüfung läuft: python2-future-0.15.2-7.el7.noarch                                                                                                                    1/1

Installiert:
  python2-future.noarch 0:0.15.2-7.el7

Komplett!
rns root@sogo ~ # python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from html import escape
>>>

As you can see, my import error goes away by installing the future package like said before. Did you install the correct package?

**Comment by croessner** [comment]
Did you really install the correct future package?

<pre>
rns root@sogo ~ # python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from html import escape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named html
>>> import future
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named future
>>>
rns root@sogo ~ # yum search future
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.hosteurope.de
 * epel: ftp.uni-stuttgart.de
 * extras: ftp.hosteurope.de
 * updates: ftp.hosteurope.de
============================================================================= N/S matched: future =============================================================================
python-futures.noarch : Backport of the concurrent.futures package from Python 3.2
python2-future.noarch : Easy, clean, reliable Python 2/3 compatibility
rubygem-vcr.noarch : Record test suite HTTP interactions and replay during future test runs

  only-Übereinstimmungen in Name und Zusammenfassung, «Alles suchen» für vollständige Suche.
rns root@sogo ~ # yum -y install python2-future.noarch
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.hosteurope.de
 * epel: ftp.uni-stuttgart.de
 * extras: ftp.hosteurope.de
 * updates: ftp.hosteurope.de
Abhängigkeiten werden aufgelöst
--> Transaktionsprüfung wird ausgeführt
---> Paket python2-future.noarch 0:0.15.2-7.el7 markiert, um installiert zu werden
--> Abhängigkeitsauflösung beendet

Abhängigkeiten aufgelöst

===============================================================================================================================================================================
 Package                                        Arch                                   Version                                      Paketquelle                          Größe
===============================================================================================================================================================================
Installieren:
 python2-future                                 noarch                                 0.15.2-7.el7                                 epel                                 797 k

Transaktionsübersicht
===============================================================================================================================================================================
Installieren  1 Paket

Gesamte Downloadgröße: 797 k
Installationsgröße: 3.6 M
Downloading packages:
python2-future-0.15.2-7.el7.noarch.rpm                                                                                                                  | 797 kB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installieren     : python2-future-0.15.2-7.el7.noarch                                                                                                                    1/1
  Überprüfung läuft: python2-future-0.15.2-7.el7.noarch                                                                                                                    1/1

Installiert:
  python2-future.noarch 0:0.15.2-7.el7

Komplett!
rns root@sogo ~ # python
Python 2.7.5 (default, Nov 20 2015, 02:00:19)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from html import escape
>>>
</pre>

**Comment by jpaechnatz** [comment]
I think I missed the 2 in python2-future, omg.  m( *facepalm* - sorry.

Now it works!

Could I change the name of the resulting mobile.config file? it delivers "company.mobileconfig"

**Comment by croessner** [comment]
You can only modify the name in the code itself. There is no such option. What is wrong with the file-name? It is nowhere displayed. You won't see it on OS X nor on iOS. So it is just a useless name :-)

**Comment by jpaechnatz** [comment]
Ah ok I see. EMailAccountDescription appears a "Profile Name". Fine. ;-)

**Comment by setiseta** [comment]
I get a similar error at the moment.
```
File "/usr/lib/automx/automx_wsgi.py", line 43, in <module>
  from automx.config import Config
ImportError: No module named 'automx'
```

It seems to be a problem since updated to ubuntu 16.10
any help would be appreciated

**Comment by wrosenauer** [comment]
Same on openSUSE Leap 42.x with installed python-futures.
Which html import module is required exactly. Probably it does not even exist as a package in openSUSE yet?

**Comment by croessner** [comment]
I will investigate this later this week. Sorry, I am sick at the moment

**Comment by wrosenauer** [comment]
To get it work on openSUSE some python packages are required which are not yet part of every maintained openSUSE version. They will only be available starting with Leap 42.3 and are already in Tumbleweed. (Affected: configparser, future and ipaddress modules)

**Comment by setiseta** [comment]
Something news on this?
Any hints how to get it work on ubntu 16.04?

**Comment by muelli** [comment]
@setiseta Ubuntu has a package: https://packages.ubuntu.com/search?keywords=automx.

**Comment by ak47-design** [comment]
Hi, i have another Problem on CentOS7 maybe anyone can help.

mod_wsgi (pid=11346): Exception occurred processing WSGI script '/usr/lib/automx/automx_wsgi.py'.
  File "/usr/lib/automx/automx_wsgi.py", line 71
    print(e, file=environ["wsgi.errors"])
                 ^
SyntaxError: invalid syntax


And at the beginning i had Problems with python ipaddress module, because in CentOS 7 its called ipaddr. So i replaced 3 times the word ipaddress to ipaddr in the file: /usr/lib64/python2.7/automx/config.py

Please HELP!

**Comment by croessner** [comment]
Did you install the python future module?

**Comment by ak47-design** [comment]
Hi @croessner 

yes it's installed, here is the List of installed python software:

python-ethtool-0.8-5.el7.x86_64
python-gofer-2.7.6-1.el7.noarch
python-gofer-proton-2.7.6-1.el7.noarch
python-pulp-rpm-common-2.8.7-1.el7.noarch
python-IPy-0.75-6.el7.noarch
dbus-python-1.1.1-9.el7.x86_64
python-iniparse-0.4-9.el7.noarch
newt-python-0.52.15-4.el7.x86_64
python-clufter-0.50.4-1.el7.x86_64
python-pyasn1-0.1.6-2.el7.noarch
python-zope-component-4.1.0-1.el7.noarch
python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
python-requests-2.6.0-1.el7_1.noarch
python2-pyrfc3339-1.0-2.el7.noarch
python-pycurl-7.19.0-17.el7.x86_64
python-cryptography-0.8.2-1.el7.x86_64
python-m2ext-0.1-4.el7.x86_64
python-dateutil-1.5-7.el7.noarch
python-dmidecode-3.10.13-11.el7.x86_64
python-rhsm-certificates-1.17.9-1.el7.x86_64
python-rhsm-1.17.9-1.el7.x86_64
python-qpid-proton-0.14.0-2.el7.x86_64
python-isodate-0.5.0-4.pulp.el7.noarch
python-pulp-agent-lib-2.8.7-1.el7.noarch
libsemanage-python-2.1.10-18.el7.x86_64
audit-libs-python-2.4.1-5.el7.x86_64
python-2.7.5-34.el7.x86_64
python-decorator-3.4.0-3.el7.noarch
libselinux-python-2.2.2-6.el7.x86_64
python-slip-dbus-0.4.0-2.el7.noarch
python-pyudev-0.15-7.el7.noarch
python-configobj-4.7.2-7.el7.noarch
python-urlgrabber-3.10-7.el7.noarch
rpm-python-4.11.3-17.el7.x86_64
python2-futures-3.0.5-1.el7.noarch
policycoreutils-python-2.2.5-20.el7.x86_64
python-lxml-3.2.1-4.el7.x86_64
python-six-1.9.0-2.el7.noarch
python-parsedatetime-1.5-3.el7.noarch
python-zope-event-4.0.3-2.el7.noarch
python2-configargparse-0.10.0-1.el7.noarch
python-backports-1.0-8.el7.x86_64
python-setuptools-0.9.8-4.el7.noarch
python-urllib3-1.10.2-2.el7_1.noarch
python-ply-3.4-10.el7.noarch
python-cffi-0.8.6-2.el7.x86_64
python-enum34-1.0.4-1.el7.noarch
python2-certbot-0.14.1-3.el7.noarch
python-augeas-0.5.0-2.el7.noarch
uwsgi-plugin-python-2.0.15-1.el7.x86_64
python-memcached-1.48-4.el7.noarch
python-configparser-3.5.0b2-1.el7.noarch
python-pulp-common-2.8.7-1.el7.noarch
python-libs-2.7.5-34.el7.x86_64
python-slip-0.4.0-2.el7.noarch
python-perf-3.10.0-327.el7.x86_64
python-zope-interface-4.0.5-4.el7.x86_64
python-chardet-2.2.1-1.el7_1.noarch
python2-mock-1.0.1-9.el7.noarch
python-ndg_httpsclient-0.3.2-1.el7.noarch
python-pycparser-2.14-1.el7.noarch
python2-dialog-3.3.0-6.el7.noarch
python-psutil-2.2.1-1.el7.x86_64
python2-future-0.16.0-2.el7.noarch
python2-acme-0.14.1-1.el7.noarch
python2-certbot-apache-0.14.1-1.el7.noarch
python-ipaddr-2.1.9-5.el7.noarch

**Comment by croessner** [comment]
Hvae you modified the wsgi python script at the top of the file? If an error like this is shown, it seems something goes wrong with the import of the future statement:

...
 18 from __future__ import absolute_import
 19 from __future__ import division

 20 from __future__ import print_function       <----- introduce print()

 21 from __future__ import unicode_literals
...

Line 20 is the one that introduces the print() function.

**Comment by ak47-design** [comment]
I have nothing of that in my file "/usr/lib/automx/automx_wsgi.py"

I havent modified the import or so, i only modified ipaddress to ipaddr. Here is the import section of my file:

import os
import sys
import traceback
import logging

from html import escape
from io import StringIO
from lxml import etree
from lxml.etree import XMLSyntaxError
from builtins import int, str

from urllib.parse import urlparse, urlencode, parse_qs, unquote
from urllib.request import urlopen, Request
from urllib.error import HTTPError

from automx.config import Config
from automx.config import DataNotFoundException
from automx.view import View

Greetz

**Comment by croessner** [comment]
Which version of automx did you install? It seems, it is an older one. Can you please try the current master branch version, which should be stable enough, as there haven't been major changes since months.

**Comment by ak47-design** [comment]
I installed this: automx-1.1.2

But i can try another, i will reply if thats solved my Problems.

Greetz

**Comment by ak47-design** [comment]
Ok, the mistakes are gone with the master version.

But i have new one in automx.log:

2017-08-04 10:15:48,091 ERROR: Traceback (most recent call last):
  File "/usr/lib/automx/automx_wsgi.py", line 236, in application
    if data.memcache.allow_client():
  File "/usr/lib64/python2.7/automx/config.py", line 958, in allow_client
    if self.__is_trusted_network():
  File "/usr/lib64/python2.7/automx/config.py", line 997, in __is_trusted_network
    a = ipaddr.ip_address(self.__client.decode("utf-8"))
AttributeError: 'module' object has no attribute 'ip_address'

Greetz

**Comment by ak47-design** [comment]
Forget it ... My fault.

My system havent shown python module ipaddress in standard repositories, after i installed it from: http://mirror.centos.org/centos/7/os/x86_64/Packages/ it works.

Thanks a lot @croessner 

Greetz
