### ISSUE TITLE
Send email address as auth_identity

### ISSUE THREAD

**Issue by beboobailey** [sys4/automx#31]
I am utilizing this script to auto-configure virtual domains hosted on a single server. All of the mailboxes need to use their full email address as their login. I see you can specify *_auth_identity but can you have that resolve to the email address passed?

**Comment by croessner** [comment]
This depends on your configuration ;-) automx is very dynamic. Can you paste a sample config that you try to develop?

**Comment by croessner** [comment]
I think you want %s for *_auth_identity

**Comment by HausInteractive** [comment]
We have the same situation as beboobailey where we would like to define the <LoginName> as user@domain.com. 

We have added this to automx.conf:

`service_auth_identity = %s`

...but automx is only outputting the equivalent of %u. 

The config file does contain values for provider and domain, one of which is what we presume is being used to populate the the domain portion of the identity.

We have the following set:

`domains = domain.com`
`logfile = /var/log/automx/automx.log`

After restarting apache and running the following command no log file is generated so we can't see if a problem was reported:

`automx-test user@domain.com`

Does anyone have an idea of what step or configuration might be missing in this process?

**Comment by Clevero** [comment]
*_auth_identity = %s

like
```
imap_auth_identity = %s
```

and

```
pop_auth_identity = %s
```

Is working fine on my host. Thanks!
