### ISSUE TITLE
[New] Certificate error on mail.automx.org

### ISSUE THREAD

**Issue by strarsis** [sys4/automx#39]
When trying to visit https://mail.automx.org/ I get a certificate error, 
I have to ignore the certificate error in order to view the site.
When revisiting the site afterwards the server refuses connection (ERR_CONNECTION_REFUSED).

**Comment by croessner** [comment]
Uhh. We really must fix the site and the demo service. Will see, if I can get things done next week

**Comment by onlime** [comment]
yep, seriously! There's that other guy who is still waiting for the demo service and the iOS provisioning page. :)
just announced Automx at Onlime today, though: http://onli.me/automx
Thx!

**Comment by strarsis** [comment]
@croessner, @onlime: Now I get a ERR_CONNECTION_REFUSED immediately. Any news on this?

**Comment by onlime** [comment]
@strarsis AFAIK, https://mail.automx.org demo is still not working. @croessner any news about this?

**Comment by croessner** [comment]
Sorry. I was sick for several weeks and I will return to work on Monday. Then I will investigate the issues

**Comment by onlime** [comment]
oh, well, Gute Besserung!! Hope you are doing great again. and no problem about this delay.

**Comment by nenonano** [comment]
the demo is still unavailable, any new?
