### ISSUE TITLE
Documentation Missing syntax for Microsoft SPA settings

### ISSUE THREAD

**Issue by HausInteractive** [sys4/automx#40]
We have searched the documentation, config files and complete mailing list archives and have not found any information on how one would set SPA to "off" using automx. We are using Dovecot IMAP and do not support Microsoft Secure Password Authentication and yet the files being generated by automx have <SPA>On.

We have tried guessing based on the formatting of other options but have been unsuccessful. 

Can the documentation have some corner cases such as this one added?

**Comment by croessner** [comment]
It should be a setting like

```
smtp_auth = cleartext
```
that disables SPA. Can you please verify this and report back, if it solved your problem?

Christian

**Comment by croessner** [comment]
Sorry, it is "plaintext", not "cleartext"

**Comment by HausInteractive** [comment]
Thank you for the reply. 'plaintext' did, indeed, work. 

We were under the impression that SPA was independent from other password encryption methods. Instead it seems as though 'auth' is either a synonym for 'SPA', or presumes that all passwords should be encrypted using whatever local methods are available eg: SPA for Outlook and another method (if available) for other mail clients.
