### ISSUE TITLE
Problem with new Office365 Outlook 2016 version new wizard autodiscover.json

### ISSUE THREAD

**Issue by p2107** [sys4/automx#44]
Microsoft have released a new version of Outlook with new account wizard that does not use the current autodiscover function. It now uses some json based function. 

It would really be good if it could be implemented partially like mailcow see https://github.com/mailcow/mailcow-dockerized/pull/636

**Comment by InToSSH** [comment]
I did some digging. Wasn't able to solve this, but when I visited this address on one of Exchange servers I got this. Request URL:
`https://autodiscover.example.com/autodiscover/autodiscover.json?Email=user%40example.com&Protocol=ActiveSync&RedirectCount=0`

For the Protocol in the GET request it's allowed to use ActiveSync or Ews.

ActiveSync gave me this response:
```
{
Protocol: "ActiveSync",
Url: "https://outlook.example.com/Microsoft-Server-ActiveSync"
}
```
And Ews this response:
```
{
Protocol: "Ews",
Url: "https://outlook.example.com/EWS/Exchange.asmx"
}
```
After visiting the ActiveSync address from the response, it askes for login using Basic Auth. I filled user's credentials, but after loading for a while it gave me this error:
`Exception Details: Microsoft.Exchange.AirSync.AirSyncPermanentException: DeviceIdMissingOrInvalid:'' `
I tried putting `DeviceId` as GET parameter as well as header, but nothing works or I don't know the correct value.

Visiting the Ews URL it creates a service on the server which allowes you to generate configuration and a code which you can use in your program, basically creating an Exchange instance I would guess.
The response looks like this: [https://vgy.me/kAworE.png](https://vgy.me/kAworE.png)
I am not that familiar with Exchange, but somebody might use it or help me reverse engineer this.
