### ISSUE TITLE
new release needed

### ISSUE THREAD

**Issue by DerDakon** [sys4/automx#53]
Given that Python2 support will end in a month it would be good to have an official release that supports Python3.

**Comment by croessner** [comment]
Current branch is at croessner/automx. I am working on it. 

Von unterwegs aus gesendet
-- 
Rößner-Network-Solutions
Karl-Bröger-Str. 10, 36304 Alsfeld
Fax: +49 6631 78823409, Mobil: +49 171 9905345
USt-IdNr.: DE225643613, https://roessner.website
PGP Fingerprint: 8FB3 132F 85D8 C9C7 A9F1  9A3F 5183 D46C B885 897E

**Comment by DerDakon** [comment]
That one needs a rebase ;)
