### ISSUE TITLE
Exception occurred processing WSGI script (centos8,no venv,mod_wsgi,)

### ISSUE THREAD

**Issue by Nuwanjith** [sys4/automx#54]
[djanfo conf.txt](https://github.com/sys4/automx/files/4360828/djanfo.conf.txt)
[wsgi.txt](https://github.com/sys4/automx/files/4360829/wsgi.txt)
[mysite-error.txt](https://github.com/sys4/automx/files/4360833/mysite-error.txt)

**Comment by rseichter** [comment]
Please don't take this the wrong way, but I have to be blunt: As is stands now, this incident report is useless. There is no description of what you are trying to do, what you expected to happen, and what happened instead.

I had a cursory glance at the attached files anyway, and the following caught my eye:

* automx2 neither supports nor requires Django.
* automx2 requires Python 3.7 or later, your log shows 3.6.
* As far as I know there is no pre-made package for CentOS 8 (I am sure nobody ever contacted me about having written one), so you need to use a virtual Python environment, as described in the automx2 documentation.
